slnShoppingForum/prjShoppingForum/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tw.com.essentialoil.Controllers
{
    public class CommonController : Controller
    {
        // GET: Commer
        public ActionResult Index()
        {
            return View();
        }
    }
}

slnShoppingForum/prjShoppingForum/Controllers/NewsController.cs
using prjShoppingForum.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tw.com.essentialoil.Controllers
{
    public class NewsController : Controller
    {
        dbShoppingForumEntities db = new dbShoppingForumEntities();
        // GET: News
        //消息後台
        public ActionResult List()
        {
            var t = from i in db.tNews
                    select i;
            List<tNew> tt = t.ToList();

            return View(t);
        }

        //新增文章
        public ActionResult New()
        {
            return View(new tNew());
        }
        [HttpPost]
        public ActionResult New(string tmp)
        {
            dbShoppingForumEntities db = new dbShoppingForumEntities();
            //db.tNews.Add(tmp);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        //刪除題目
        public ActionResult Delete(int fId)
        {
            dbShoppingForumEntities db = new dbShoppingForumEntities();
            tNew q = db.tNews.FirstOrDefault(p => p.fNewsId == fId);
            db.tNews.Remove(q);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        //編輯題目
        public ActionResult Edit(int fId)
        {
            tNew prod = db.tNews.FirstOrDefault(p => p.fNewsId == fId);
            if (prod == null)
                return RedirectToAction("List");
            return View(new tNew());
        }
        [HttpPost]
        public ActionResult Edit(tNew p)
        {
            dbShoppingForumEntities db = new dbShoppingForumEntities();
            tNew prod = db.tNews.FirstOrDefault(t => t.fNewsId == p.fNewsId);
            if (prod != null)
            {
                prod.fClass = p.fClass;
                prod.fNewsTitle = p.fNewsTitle;
                prod.fNewsDesc = p.fNewsDesc;
                prod.fNewsArticle = p.fNewsArticle;
                prod.fNewsTag = p.fNewsTag;
                prod.fGet_No = p.fGet_No;
                prod.fAddUser = p.fAddUser;
                prod.fChangUser = p.fChangUser;
                prod.fDeleteUser = p.fDeleteUser;
                prod.fApproved = p.fApproved;
                prod.fNewsStart = p.fNewsStart;
                prod.fNewsEnd = p.fNewsEnd;
                db.SaveChanges();
            }
            return RedirectToAction("List");
        }


    }
}

slnShoppingForum/prjShoppingForum/Controllers/ScoreController.cs
using prjShoppingForum.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tw.com.essentialoil.Controllers
{
    public class ScoreController : Controller
    {
        dbShoppingForumEntities db = new dbShoppingForumEntities();

        // GET: Score
        // 積分後台介面
        public ActionResult List()
        {

            var t = (from i in db.tScores
                    where i.fId == 1      //TODO
                    select i).FirstOrDefault();

            //List<tScore> tt = t.ToList();

            return View(t);
        }
        //新增題目
        public ActionResult New()
        {
            return View(new tScore());
        }
        [HttpPost]
        public ActionResult New(tScore p)
        {
            dbShoppingForumEntities db = new dbShoppingForumEntities();
            db.tScores.Add(p);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        //刪除積分
        public ActionResult Delete(int fId)
        {
        dbShoppingForumEntities db = new dbShoppingForumEntities();
        tScore q = db.tScores.FirstOrDefault(p => p.fId == fId);
        db.tScores.Remove(q);
                db.SaveChanges();
            return RedirectToAction("List");
    }

    //編輯題目
    public ActionResult Edit(int fId)
        {
            tScore prod = db.tScores.FirstOrDefault(p => p.fId == fId);
            if (prod == null)
                return RedirectToAction("List");
            return View(new tScore());
        }
        [HttpPost]
        public ActionResult Edit(tScore p)
        {
            dbShoppingForumEntities db = new dbShoppingForumEntities();
            tScore prod = db.tScores.FirstOrDefault(t => t.fId == p.fId);
            if (prod != null)
            {
                prod.fId = p.fId;
                prod.fScore = p.fScore;
                prod.fActiveScore = p.fActiveScore;
                prod.fQuestionScore = p.fQuestionScore;
                prod.fScoreDate = p.fScoreDate;
                prod.fAuthTestFlag = p.fAuthTestFlag;

                db.SaveChanges();
            }
            return RedirectToAction("List");
        }
    }
}

slnShoppingForum/prjShoppingForum/Views/Score/Delete.cshtml
@model prjShoppingForum.Models.Entity.tScore

@{
    ViewBag.Title = "刪除積分紀錄";
}

<h2>刪除</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>tScore</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.fScore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fScore)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fActiveScore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fActiveScore)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fQuestionScore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fQuestionScore)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fScoreDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fScoreDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fAuthTestFlag)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fAuthTestFlag)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.tUserProfile.fName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tUserProfile.fName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("返回", "List")
        </div>
    }
</div>

slnShoppingForum/prjShoppingForum/Views/Score/Edit.cshtml
@model prjShoppingForum.Models.Entity.tScore

@{
    ViewBag.Title = "編輯積分紀錄";
}

<h2>編輯積分紀錄</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tScore</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.fUserId)

        <div class="form-group">
            @Html.LabelFor(model => model.fScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fScore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fActiveScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fActiveScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fActiveScore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fQuestionScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fQuestionScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fQuestionScore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fScoreDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fScoreDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fScoreDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fAuthTestFlag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.fAuthTestFlag)
                    @Html.ValidationMessageFor(model => model.fAuthTestFlag, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回", "List")
</div>

slnShoppingForum/prjShoppingForum/Views/Score/List.cshtml
@model prjShoppingForum.Models.Entity.tScore

@{
    ViewBag.Title = "異動積分表";
}

<h2>積分表異動</h2>

<p>
    @Html.ActionLink("新增", "New")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.tUserProfile.fName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fScoreDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fScore)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fActiveScore)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fQuestionScore)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fAuthTestFlag)
        </th>
        <th></th>
    </tr>

    
    
    <tr>
        <td>
            @Html.DisplayFor(modelItem => modelItem.tUserProfile.fName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.fScoreDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.fScore)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.fActiveScore)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.fQuestionScore)
        </td>
        <td>
            @Html.DisplayFor(modelItem => modelItem.fAuthTestFlag)
        </td>
        <td>
            @Html.ActionLink("編輯", "Edit", new { id = Model.fId }, new { @class = "btn btn-Edit" }) |
            @Html.ActionLink("Details", "Details", new { id = Model.fId }) |
            @Html.ActionLink("刪除", "Delete", new { id = Model.fId }, new { @class = "btn btn-danger", onclick = "return confirm('確定要刪除嗎?')" })
        </td>
    </tr>
    

</table>


<div>

    <p>@Html.ActionLink("系統目錄", "Index", "Common")</p>

</div>

slnShoppingForum/prjShoppingForum/Views/Score/New.cshtml
@model prjShoppingForum.Models.Entity.tScore

@{
    ViewBag.Title = "新增積分";
}

<h2>新增</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tScore</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.fId, "fId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("fId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fUserId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fScore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fActiveScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fActiveScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fActiveScore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fQuestionScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fQuestionScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fQuestionScore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fScoreDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fScoreDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fScoreDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fAuthTestFlag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.fAuthTestFlag)
                    @Html.ValidationMessageFor(model => model.fAuthTestFlag, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回", "List")
</div>