slnShoppingForum/prjShoppingForum/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace prjShoppingForum.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

slnShoppingForum/prjShoppingForum/Controllers/NewsController.cs
using prjShoppingForum.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tw.com.essentialoil.Controllers
{
    public class NewsController : Controller
    {
        dbShoppingForumEntities db = new dbShoppingForumEntities();
        // GET: News
        //消息後台
        public ActionResult List()
        {
            var t = from i in db.tNews
                    select i;
            List<tNew> tt = t.ToList();

            return View(t);
        }

        //新增文章
        public ActionResult New()
        {
            return View(new tNew());
        }
        [HttpPost]
        public ActionResult New(string tmp)
        {
            dbShoppingForumEntities db = new dbShoppingForumEntities();
            //db.tNews.Add(tmp);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        //刪除題目
        public ActionResult Delete(int fId)
        {
            dbShoppingForumEntities db = new dbShoppingForumEntities();
            tNew q = db.tNews.FirstOrDefault(p => p.fNewsId == fId);
            db.tNews.Remove(q);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        //編輯題目
        public ActionResult Edit(int fId)
        {
            tNew prod = db.tNews.FirstOrDefault(p => p.fNewsId == fId);
            if (prod == null)
                return RedirectToAction("List");
            return View(new tNew());
        }
        [HttpPost]
        public ActionResult Edit(tNew p)
        {
            dbShoppingForumEntities db = new dbShoppingForumEntities();
            tNew prod = db.tNews.FirstOrDefault(t => t.fNewsId == p.fNewsId);
            if (prod != null)
            {
                prod.fClass = p.fClass;
                prod.fNewsTitle = p.fNewsTitle;
                prod.fNewsDesc = p.fNewsDesc;
                prod.fNewsArticle = p.fNewsArticle;
                prod.fNewsTag = p.fNewsTag;
                prod.fGet_No = p.fGet_No;
                prod.fAddUser = p.fAddUser;
                prod.fChangUser = p.fChangUser;
                prod.fDeleteUser = p.fDeleteUser;
                prod.fApproved = p.fApproved;
                prod.fNewsStart = p.fNewsStart;
                prod.fNewsEnd = p.fNewsEnd;
                db.SaveChanges();
            }
            return RedirectToAction("List");
        }


    }
}

slnShoppingForum/prjShoppingForum/Controllers/USer/FrontUser/FrontUserProfileController.cs
using prjShoppingForum.Models.Entity;

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using tw.com.essentialoil.User.Models;

namespace tw.com.essentialoil.Controllers.FrontUser
{
    public class FrontUserProfileController : Controller
    {
        private dbShoppingForumEntities db = new dbShoppingForumEntities();

        // GET: tUserProfile

        public ActionResult New()
        {
            return View();
        }
        [HttpPost]
        public ActionResult New(tUserProfile c)
        {
            db.tUserProfiles.Add(c);
            db.SaveChanges();
            return RedirectToAction("Home");
        }
        public ActionResult UserEdit(string g)
        {
            if(Session[UserDictionary.S_CURRENT_LOGINED_USER]!=null)
            g = Session[UserDictionary.S_CURRENT_LOGINED_USER].ToString();
            tUserProfile cust = (new dbShoppingForumEntities()).tUserProfiles.FirstOrDefault(c => c.fUserId == g);
            if (cust == null)
                return RedirectToAction("Home");
            return View(cust);
        }
        [HttpPost]
        public ActionResult UserEdit(string fName, string fTel, string fPhone,string fCity,string fAddress)
        {
            var g = Session[UserDictionary.S_CURRENT_LOGINED_USER].ToString();
            tUserProfile cust = db.tUserProfiles.FirstOrDefault(t => t.fUserId == g);
            if (cust != null)
            {
                cust.fName = fName;
                cust.fTel = fTel;
                cust.fPhone = fPhone;
                cust.fCity = fCity;
                cust.fAddress = fAddress;
                db.SaveChanges();
            }
            return RedirectToAction("Home");
        }

        //LogIn
        Random r = new Random();
        public async Task<ActionResult> Index()
        {
            var tUserProfile = db.tUserProfiles.Include(t => t.tForumAuth).Include(t => t.tScore).Include(t => t.tUserLog);
            return View(await tUserProfile.ToListAsync());
        }

        public ActionResult Home()
        {
            if (Session[UserDictionary.S_CURRENT_LOGINED_USER] == null)
                return RedirectToAction("Login");
            else
            {
                var g = Session[UserDictionary.S_CURRENT_LOGINED_USER].ToString();
                var detail = db.tUserProfiles.Where(p => p.fName == g).Select(q=>q);
                return View(detail);
            }
        }
        public ActionResult Login(CLoginData data)
        {
            if (Session[UserDictionary.S_AUTHENTICATED_CODE] == null)
            {
                Session[UserDictionary.S_AUTHENTICATED_CODE] =
                    r.Next(0, 10).ToString() +
                    r.Next(0, 10).ToString() +
                    r.Next(0, 10).ToString() +
                    r.Next(0, 10).ToString();
            }
            if (data != null)
            {
                var cust = from d in db.tUserProfiles
                           where d.fUserId == data.fUserId
                           select d.fPassword;
                if (cust != null)
                {
                    if (cust.Contains(data.fPassword))
                    {
                        var Ufid = db.tUserProfiles.FirstOrDefault(u => u.fUserId == data.fUserId).fId;
                        //var UfId = from d in db.tUserProfile
                        //              where d.fUserId == data.fUserId
                        //              select d.fId;
                        if (data.fVeriCode.Equals(Session[UserDictionary.S_AUTHENTICATED_CODE].ToString()) && Session[UserDictionary.S_AUTHENTICATED_CODE] != null)
                        {
                            Session[UserDictionary.S_CURRENT_LOGINED_USER] = data.fUserId;
                            Session[UserDictionary.S_CURRENT_LOGINED_USERfid] = Ufid;
                            return RedirectToAction("Home");
                        }
                        else
                            ViewBag.ErrorMessage = "驗證碼不符";
                    }
                    else ViewBag.ErrorMessage = "密碼不正確";
                }
            }
            return View();
        }

























        //自動產生
        // GET: tUserProfiles/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tUserProfile tUserProfile = await db.tUserProfiles.FindAsync(id);
            if (tUserProfile == null)
            {
                return HttpNotFound();
            }
            return View(tUserProfile);
        }

        // GET: tUserProfiles/Create
        public ActionResult Create()
        {
            ViewBag.fId = new SelectList(db.tForumAuths, "fId", "fAuthBlackList");
            ViewBag.fId = new SelectList(db.tScores, "fId", "fId");
            ViewBag.fId = new SelectList(db.tUserLogs, "fId", "fUserIP");
            return View();
        }

        // POST: tUserProfiles/Create
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "fId,fUserId,fPassword,fPasswordSalt,fName,fGender,fBirthday,fTel,fPhone,fCity,fAddress,fPhoto,fCreateDate,fScore,fAuth,fAuthPost,fAuthReply")] tUserProfile tUserProfile)
        {
            if (ModelState.IsValid)
            {
                db.tUserProfiles.Add(tUserProfile);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.fId = new SelectList(db.tForumAuths, "fId", "fAuthBlackList", tUserProfile.fId);
            ViewBag.fId = new SelectList(db.tScores, "fId", "fId", tUserProfile.fId);
            ViewBag.fId = new SelectList(db.tUserLogs, "fId", "fUserIP", tUserProfile.fId);
            return View(tUserProfile);
        }

        // GET: tUserProfiles/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tUserProfile tUserProfile = await db.tUserProfiles.FindAsync(id);
            if (tUserProfile == null)
            {
                return HttpNotFound();
            }
            ViewBag.fId = new SelectList(db.tForumAuths, "fId", "fAuthBlackList", tUserProfile.fId);
            ViewBag.fId = new SelectList(db.tScores, "fId", "fId", tUserProfile.fId);
            ViewBag.fId = new SelectList(db.tUserLogs, "fId", "fUserIP", tUserProfile.fId);
            return View(tUserProfile);
        }

        // POST: tUserProfiles/Edit/5
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "fId,fUserId,fPassword,fPasswordSalt,fName,fGender,fBirthday,fTel,fPhone,fCity,fAddress,fPhoto,fCreateDate,fScore,fAuth,fAuthPost,fAuthReply")] tUserProfile tUserProfile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tUserProfile).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.fId = new SelectList(db.tForumAuths, "fId", "fAuthBlackList", tUserProfile.fId);
            ViewBag.fId = new SelectList(db.tScores, "fId", "fId", tUserProfile.fId);
            ViewBag.fId = new SelectList(db.tUserLogs, "fId", "fUserIP", tUserProfile.fId);
            return View(tUserProfile);
        }

        // GET: tUserProfiles/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tUserProfile tUserProfile = await db.tUserProfiles.FindAsync(id);
            if (tUserProfile == null)
            {
                return HttpNotFound();
            }
            return View(tUserProfile);
        }

        // POST: tUserProfiles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            tUserProfile tUserProfile = await db.tUserProfiles.FindAsync(id);
            db.tUserProfiles.Remove(tUserProfile);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

slnShoppingForum/prjShoppingForum/Views/FrontUserProfile/Home.cshtml
@model IEnumerable<prjShoppingForum.Models.Entity.tUserProfile>
@using prjShoppingForum.Models.Entity;
@using tw.com.essentialoil.User.Models;
@{
    ViewBag.Title = "Home";
}

歡迎 @Session[UserDictionary.S_CURRENT_LOGINED_USER] 登入
您的會員編號為 @Session[UserDictionary.S_CURRENT_LOGINED_USERfid]
<h2>Home</h2>
<p>@Html.ActionLink("編輯會員資訊", "UserEdit", "FrontUserProfile")</p>
<form>
    @{
        foreach (var t in Model)
        {
            <p>姓名:@t.fName</p>
            <p>生日:@t.fBirthday</p>
            <p>性別:@t.fGender</p>
            <p>市話:@t.fTel</p>
            <p>手機:@t.fPhone</p>
            <p>城市:@t.fCity</p>
            <p>地址:@t.fAddress</p>
        }
    }
</form>

slnShoppingForum/prjShoppingForum/Views/FrontUserProfile/Login.cshtml
@using tw.com.essentialoil.User.Models;

@{
    ViewBag.Title = "Login";
    string pic = " ";

}

<h2>Login</h2>

@using (Html.BeginForm())
{
    <p>
        輸入使用者帳號<br />
        @Html.TextBox("fUserId")
    </p>
    <p>
        密碼<br />
        @Html.Password("fPassword")
    </p>
    <p>
        輸入驗證碼<br />
        @if (Session[UserDictionary.S_AUTHENTICATED_CODE] != null)
        {
            @Html.TextBox("fVeriCode")
            pic = Session[UserDictionary.S_AUTHENTICATED_CODE].ToString().Substring(0, 1) + ".png";
            @:<img src="/Images/@pic" width="60" />
            pic = Session[UserDictionary.S_AUTHENTICATED_CODE].ToString().Substring(1, 1) + ".png";
            @:<img src="/Images/@pic" width="60" />
            pic = Session[UserDictionary.S_AUTHENTICATED_CODE].ToString().Substring(2, 1) + ".png";
            @:<img src="/Images/@pic" width="60" />
            pic = Session[UserDictionary.S_AUTHENTICATED_CODE].ToString().Substring(3, 1) + ".png";
            @:<img src="/Images/@pic" width="60" />
        }
    </p>
    if (Session[UserDictionary.S_CURRENT_LOGINED_USER] != null)
    {
        <p>@Session[UserDictionary.S_CURRENT_LOGINED_USER].ToString()</p>

    }
    <p>
        <input type="submit" value="送出" />
    </p>
}

slnShoppingForum/prjShoppingForum/Views/FrontUserProfile/New.cshtml
@*@model EssentialOiltest.Models.Entity.tUserProfile*@

@{
    ViewBag.Title = "New";
}

<h2>加入會員</h2>
@using (Html.BeginForm())
{
    @*@Html.EditorForModel();*@
    <hr />
    <form action="~/Home/Login" method="post" name="LoginForm">
        <h4>帳號:</h4>
        <input type="text" name="userId" />
        <h4>密碼:</h4>
        <input type="password" name="userPwd" />
        <h4>姓名:</h4>
        <input type="text" name="userName" />
        <h4>性別:</h4>
        <input type="text" name="userGender" />
        <h4>生日:</h4>
        <input type="text" name="userBirthday" placeholder="e.g.:2020/02/09" />
        <h4>電話:</h4>
        <input type="text" name="userTel" />
        <h4>手機:</h4>
        <input type="text" name="userPhone" />
        <h4>城市:</h4>
        <input type="text" name="userCity" />
        <h4>地址:</h4>
        <input type="text" name="userAddress" />

        <hr />
    </form>

    <input type="submit" name="userSignUp" value="註冊" />
    <input type="reset" value="取消" />
}

@section scripts{
    <script>
        //找到要控制的HTML標籤
        //TODO:註冊完導向首頁
        //$('form[name="userSignUp"]').click(function () {
        //    )

        //})



    </script>


}

slnShoppingForum/prjShoppingForum/Views/FrontUserProfile/UserEdit.cshtml
@model prjShoppingForum.Models.Entity.tUserProfile
@{
    ViewBag.Title = "UserEdit";
}

<h2>編輯會員資料</h2>

<form method="post" name="editform">
    <p>
        姓名<br /><input type="text" name="fName" value="@Model.fName" />
    </p>
    <p>
        電話<br /><input type="text" name="fTel" value="@Model.fTel" />
    </p>
    <p>
        手機<br /><input type="text" name="fPhone" value="@Model.fPhone" />
    </p>
    <p>
        手機<br /><input type="text" name="fCity" value="@Model.fCity" />
    </p>
    <p>
        地址<br /><input type="text" name="fAddress" value="@Model.fAddress" />
    </p>
    <p>
        <input type="submit" value="送出" name="editbutton"/>
    </p>

</form>

@section scripts{
    <script>
        //var xhr = null;
        //$('input[name="editbutton"]').addEventListener("click", function () {
        //    xhr = new XMLHttpRequest();
        //    var formData = new FormData(document.editform);
        //    xhr.open('POST', '/FrontUserProfile/UserEdit');
        //    xhr.send(formData);
        //}




    </script>
}