slnShoppingForum/prjShoppingForum/Models/Forum/CForum.cs
using prjShoppingForum.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using tw.com.essentialoil.Forum.ViewModels;

namespace tw.com.essentialoil.Forum.Models
{
    public class CForum
    {
        dbShoppingForumEntities db = new dbShoppingForumEntities();

        //Create New Post
        public void newPost(int userId, string title, string content)
        {
            tForum newForumRecord = new tForum();
            newForumRecord.fId = userId;
            newForumRecord.fPostTitle = title;
            newForumRecord.fPostContent = content;
            newForumRecord.fIsPost = true;
            newForumRecord.fCreateTime = DateTime.Now;
            newForumRecord.fUpdateTime = DateTime.Now;
            newForumRecord.fEnableFlag = true;
            newForumRecord.fTopSeq = 999;
            newForumRecord.fTotalReplyCount = 0;
            newForumRecord.fTotalViewCount = 0;

            db.tForums.Add(newForumRecord);
            
            db.SaveChanges();
        }

        //Select All Post
        public IQueryable<tForum> queryAllPost()
        {
            IQueryable<tForum> result = from i in db.tForums
                                        where i.fEnableFlag == true       //刪除的不要被select出來
                                        select i;

            return result;
        }

        //Select Post by Id
        public tForum queryPostById(int fPostId)
        {
            //TODO - 補上權限控制
            tForum result = (from i in db.tForums
                          where i.fPostId == fPostId
                          select i).FirstOrDefault();

            return result;
        }

        //Select Post By Time
        public List<tForum> queryPostByTime(DateTime prevDateTime) {
            var results = from p in db.tForums
                          where (p.fUpdateTime > prevDateTime) && (p.fEnableFlag == true)
                          select p;

            return results.ToList();
        }

        //Select 【Disable】 Post By Time
        public List<tForum> queryPostByDelTime(DateTime prevDateTime)
        {
            var results = from p in db.tForums
                          where (p.fDisableTime > prevDateTime) && (p.fEnableFlag == false)
                          select p;

            return results.ToList();
        }

        //Update Post By Id
        public void updatePostById(object fPostId, CForumCreate data)
        {
            int fId = Convert.ToInt32(fPostId);

            tForum result = (from i in db.tForums
                             where i.fPostId == fId
                             select i).FirstOrDefault();

            if (result!=null)
            {
                result.fPostTitle = data.postTitle;
                result.fPostContent = data.tmpContent;
                result.fUpdateTime = DateTime.Now;

                db.SaveChanges();
            }

        }

        //Delete Post By Id
        public void deletePostById(int fPostId)
        {
            tForum result = (from i in db.tForums
                             where i.fPostId == fPostId && i.fEnableFlag == true
                             select i).FirstOrDefault();

            if (result != null)
            {
                result.fEnableFlag = false;
                result.fEnableUserId = 1;    //TODO - 要動態產生
                result.fDisableTime = DateTime.Now;

                db.SaveChanges();
                
            }

        }

    }
}

slnShoppingForum/prjShoppingForum/Models/Forum/CReply.cs
using prjShoppingForum.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using tw.com.essentialoil.Forum.ViewModels;

namespace tw.com.essentialoil.Forum.Models
{
    public class CReply
    {
        dbShoppingForumEntities db = new dbShoppingForumEntities();
        //Create New Reply
        public void NewCommentForPost(CNewReplyCreate replyInfo, int userId)
        {
            tForumReply reply = new tForumReply();
            reply.fPostId = replyInfo.postId;
            reply.fReplyId = Guid.NewGuid().ToString();
            reply.fReplyTargetId = replyInfo.targetId;
            reply.fReplySeqNo = 0;
            reply.fId = userId;
            reply.fReplyTime = DateTime.Now;
            reply.fEnableFlag = true;
            reply.fContent = replyInfo.content;

            db.tForumReplies.Add(reply);
            db.SaveChanges();
        }

        //Create New Reply For Comment
        public void NewCommentForComment(CNewReplyCreate replyInfo, int userId)
        {
            tForumReply targetReply = (from i in db.tForumReplies
                                       where i.fReplyId == replyInfo.targetId && i.fEnableFlag == true
                                       select i).FirstOrDefault();

            if (targetReply != null)
            {
                tForumReply reply = new tForumReply();
                reply.fPostId = replyInfo.postId;
                reply.fReplyId = Guid.NewGuid().ToString();
                reply.fReplyTargetId = replyInfo.targetId;
                reply.fReplySeqNo = targetReply.fReplySeqNo + 1;
                reply.fId = userId;
                reply.fReplyTime = DateTime.Now;
                reply.fEnableFlag = true;
                reply.fContent = replyInfo.content;

                db.tForumReplies.Add(reply);
                db.SaveChanges();
            }
        }


        //Get All Reply By Id
        public List<List<tForumReply>> getReplysById(int fPostId)
        {
            List<List<tForumReply>> result = new List<List<tForumReply>>();

            //先取得該文章的所有留言
            var allReply = from m in db.tForumReplies
                           where m.fPostId == fPostId
                           select m;

            List<tForumReply> allReplyList = allReply.ToList();

            //分別取得每一個階層的留言清單，並依照建立時間排序
            //回傳結果
            //[[第一則留言的所有階層],[第二則留言的所有階層],[第三則留言的所有階層],...]
            int startNum = 0;  //階層
            if (allReplyList.Count > 0)
            {
                List<tForumReply> m_num = (from i in allReplyList
                                           where i.fReplySeqNo == startNum
                                           orderby i.fReplyTime ascending
                                           select i).ToList();

                
                for (int i = 0; i < m_num.Count; i++)
                {
                    List<tForumReply> tmpReply = new List<tForumReply>();
                    getCommentFlow(m_num[i], tmpReply);
                    result.Add(tmpReply);
                }
            }

            return result;
        }

        public void getCommentFlow(tForumReply reply, List<tForumReply> result)
        {
            result.Add(reply);
            string targetId = reply.fReplyId;
            var lvNum = (from i in db.tForumReplies
                      where i.fReplyTargetId == targetId
                      orderby i.fReplySeqNo ascending, i.fReplyTime ascending
                      select i).ToList();

            if (lvNum.Count != 0)
            {
                for (int i = 0; i < lvNum.Count; i++)
                {
                    getCommentFlow(lvNum[i], result);
                }
            }
        }

        //Get All New Reply By Time
        public List<tForumReply> getNewReplysByTime(int postId, DateTime targetTime) {

            var replys = from m in db.tForumReplies
                         where m.fEnableFlag == true && m.fPostId == postId && m.fReplyTime > targetTime
                         orderby m.fReplyTime
                         select m;

            return replys.ToList();
        }
    }
}

slnShoppingForum/prjShoppingForum/ViewModels/Forum/CForumCreate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tw.com.essentialoil.Forum.ViewModels
{
    public class CForumCreate
    {
        public string postTitle { get; set; }

        [AllowHtml]
        public string tmpContent { get; set; }
    }
}

slnShoppingForum/prjShoppingForum/ViewModels/Forum/CNewReplyCreate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace tw.com.essentialoil.Forum.ViewModels
{
    public class CNewReplyCreate
    {
        public int postId { get; set; }
        public string targetType { get; set; }
        public string targetId { get; set; }
        public string content { get; set; }
    }
}

slnShoppingForum/prjShoppingForum/ViewModels/Forum/CPostView.cs
using prjShoppingForum.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace tw.com.essentialoil.Forum.ViewModels
{
    public class CPostView
    {
        public tForum forum { get; set; }
        public List<List<tForumReply>> reply { get; set; }
    }
}

slnShoppingForum/prjShoppingForum/Controllers/ForumController.cs
//由Entity Framework產生，不改namespace
using prjShoppingForum.Models.Entity;

//------------------------------------------//
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
//------------------------------------------//

using tw.com.essentialoil.Forum.Models;
using tw.com.essentialoil.Forum.ViewModels;
using tw.com.essentialoil.Models;

namespace tw.com.essentialoil.Controllers
{
    public class ForumController : Controller
    {
        //所有文章列表
        public ActionResult List()
        {
            //一進入Action就先取出當下時間
            ViewBag.DateTime = DateTime.Now.ToString("yyyyMMddHHmmssfff");

            CForum forum = new CForum();
            
            return View(forum.queryAllPost());
        }

        //呈現文章的內容
        public ActionResult PostView(int fPostId) {
            
            //一進入Action就先取出當下時間
            ViewBag.DateTime = DateTime.Now.ToString("yyyyMMddHHmmssfff");

            CForum forum = new CForum();
            tForum tForum = forum.queryPostById(fPostId);

            CReply reply = new CReply();
            List<List<tForumReply>> replys = reply.getReplysById(fPostId);

            CPostView postview = new CPostView { forum = tForum, reply = replys };
            
            if (postview.forum != null)
            {
                string test = postview.forum.fPostContent;
                return View(postview);
            }

            
            return RedirectToAction("List");
        }

        //修改文章內容
        public ActionResult Edit(int fPostId)
        {
            Session[CDictionary.UPDATE_FORUM_ID] = fPostId;

            CForum forum = new CForum();
            tForum tForum = forum.queryPostById(fPostId);

            if (tForum != null) return View(tForum);

            return RedirectToAction("List");
        }

        //修改文章內容[POST]
        [HttpPost]
        //[ValidateInput(false)]
        public ActionResult Edit(CForumCreate vm)
        {
            if (Session[CDictionary.UPDATE_FORUM_ID] != null)
            {
                CForum forum = new CForum();
                forum.updatePostById(Session[CDictionary.UPDATE_FORUM_ID], vm);
            }

            return RedirectToAction("List");

        }

        //刪除文章
        public ActionResult Delete(int fPostId)
        {
            CForum forum = new CForum();
            forum.deletePostById(fPostId);
            
            return RedirectToAction("List");
        }


        //----------------------------Ajax----------------------------
        //新增文章
        public ActionResult Create(string title, string content)
        {
            //TODO
            //從Session讀取資料
            //判斷是否有登入，如果有登入，取得該會員的fId

            string status = "error";
            if (!String.IsNullOrWhiteSpace(title))
            {
                CForum forum = new CForum();
                forum.newPost(1, title, content);
                status = "success";
            }

            //回傳狀態
            return Content(status);
        }

        //定時更新文章List
        public ActionResult RefreshList(int lastPostId, string prevDtaetime) {

            //一進入Action就先取出當下時間
            string newTime = DateTime.Now.ToString("yyyyMMddHHmmssfff");

            //撈出更新時間在prevDateTime之後的所有文章
            DateTime targetTime = DateTime.ParseExact(prevDtaetime, "yyyyMMddHHmmssfff", CultureInfo.CurrentCulture);

            CForum forum = new CForum();
            List<tForum> forums = forum.queryPostByTime(targetTime);
            List<tForum> delForums = forum.queryPostByDelTime(targetTime);

            List<object> newForums = new List<object>();
            List<object> updateForums = new List<object>();
            List<object> deleteForums = new List<object>();

            //利用postIdList區分是更新的文章還是新增的文章
            foreach (tForum post in forums)
            {
                if ( post.fPostId > lastPostId )
                {
                    var newPost = new
                    {
                        title = post.fPostTitle,      //文章標題
                        postId = post.fPostId         //文章編號
                    };

                    newForums.Add(newPost);
                }
                else
                {
                    var updatePost = new
                    {
                        title = post.fPostTitle,      //文章標題
                        postId = post.fPostId         //文章編號
                    };

                    updateForums.Add(updatePost);
                }
            }

            //取得所有刪除的文章編號
            foreach (tForum post in delForums)
            {
                var deletePost = new
                {
                    postId = post.fPostId             //文章編號
                };

                deleteForums.Add(deletePost);
            }

            //定義回傳json
            if (forums.Count > 0)
            {
                return Json(
                    new
                    {
                        newTime = newTime,
                        newForums = newForums,
                        updateForums = updateForums,
                        deleteForums = deleteForums
                    }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(
                    new
                    {
                        newTime = newTime,
                        newForums = newForums,
                        updateForums = updateForums,
                        deleteForums = deleteForums
                    }, JsonRequestBehavior.AllowGet);
            }

        }

        //回覆文章 / 回覆回覆
        public ActionResult Reply(CNewReplyCreate replyInfo) {
            string status = "";

            //TODO
            //從Session讀取資料
            //判斷是否有登入，如果有登入，取得該會員的fId

            CReply reply = new CReply();
            if (replyInfo.targetType == "POST") reply.NewCommentForPost(replyInfo, 1);
            if (replyInfo.targetType == "COMMENT") reply.NewCommentForComment(replyInfo, 1);

            return Content(status);
        }

        //定時更新留言List
        public ActionResult RefreshReplyList(int lastPostId, string prevDtaetime)
        {

            //一進入Action就先取出當下時間
            string newTime = DateTime.Now.ToString("yyyyMMddHHmmssfff");

            //撈出更新時間在prevDateTime之後的所有留言
            DateTime targetTime = DateTime.ParseExact(prevDtaetime, "yyyyMMddHHmmssfff",CultureInfo.CurrentCulture);

            CReply reply = new CReply();
            List<tForumReply> replys = reply.getNewReplysByTime(lastPostId, targetTime);

            List<object> newReplyList = new List<object>();

            if (replys.Count > 0)
            {
                foreach (var item in replys)
                {
                    var newReply = new
                    {
                        replyId = item.fReplyId,               //自己的ID
                        replyTargetId = item.fReplyTargetId,   //回覆對象的ID
                        replySeqNo = item.fReplySeqNo,
                        replyContent = item.fContent
                    };

                    newReplyList.Add(newReply);
                }
            }

            return Json(
                new
                {
                    newTime = newTime,
                    newReplyList = newReplyList
                }, JsonRequestBehavior.AllowGet);

        }

    }
}

slnShoppingForum/prjShoppingForum/Views/Forum/Edit.cshtml
<h2>Edit</h2>

@model prjShoppingForum.Models.Entity.tForum

@{
    ViewBag.Title = "Edit";
    string result = WebUtility.HtmlDecode(Model.fPostContent);
}

<div class="PostContent" style="width:600px; height:auto; margin:auto;">
    @using (Html.BeginForm())
    {
        <div style="width: 600px; margin:20px auto;">
            標題：<br />
            <input type="text" name="postTitle" value="@Model.fPostTitle" />
            <br />
            <br />
            內文：<br />
            <div id="editor" style="height:500px">
            </div>
            <textarea id="tmpContent" name="tmpContent" style="display:none"></textarea>
            <input type="submit" value="送出" />
        </div>
    }

    <div class="targetSource" style="display:none">
        @Html.Raw(result)
    </div>
</div>

<script src="~/Scripts/Forum/QuillEditor.New_Update.Post.js"></script>
<script src="~/Scripts/Forum/EventHandle.Edit.js"></script>

slnShoppingForum/prjShoppingForum/Views/Forum/List.cshtml
@model IQueryable<prjShoppingForum.Models.Entity.tForum>

@{
    ViewBag.Title = "List";
    int lastPostId = 0;
    if (Model.ToList().Count > 0)
    {
        lastPostId = Model.Max(p => p.fPostId);
    };

}

<div style="margin:20px auto">
    <div>
        @*<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalScrollable">
            發表文章
        </button>*@

        @* From Bootstrap Example *@
        @* -------------------------------------------------------------------------------------------------- *@
        @* -------------------------------------------------------------------------------------------------- *@
        <div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog" aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-scrollable" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalScrollableTitle">編輯文章</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>

                    @* 標題區塊 *@
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroup-sizing-default">標題</span>
                        </div>
                        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" placeholder="請輸入標題" id="postTitle">
                    </div>

                    @* 編輯文章區塊 *@
                    <div class="modal-body" id="editor">

                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">離開</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal" id="confirmPost">確認發佈</button>
                    </div>
                </div>
            </div>
        </div>

        @* 紀錄上一筆的ajax時間，用來計算每次ajax的差異，不用每次全抓資料 *@
        <div id="prevGetTime" style="display:none;">@ViewBag.DateTime</div>
    </div>
</div>

<table class="table table-striped">
    <thead>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td data-postid="@item.fPostId">
                    @Html.ActionLink(item.fPostTitle, "PostView", new { fPostId = item.fPostId })
                    <br />
                    <button class="btn btn-primary">喜歡</button>
                    <button class="btn btn-primary">討厭</button>
                    <button class="btn btn-primary">分享</button>
                    <button class="btn btn-primary">收藏</button>
                    <button class="btn btn-primary">隱藏</button>
                    <button class="btn btn-primary">編輯</button>
                    <button class="btn btn-danger">停用</button>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script>
        //注意!! EventHandle.Edit 有修改，這邊也要做確認，避免兩邊IDmapping錯誤

        //建立Quill文章編輯器
        let toolbarOptions = [
            ['bold', 'italic', 'underline', 'strike'],        // toggled buttons
            ['blockquote', 'code-block'],
            [{ 'list': 'bullet' }, { 'list': 'ordered' }],
            [{ 'script': 'super' }, { 'script': 'sub' }],      // superscript/subscript
            [{ 'direction': 'rtl' }],                         // text direction
            [{ 'indent': '+1' }, { 'indent': '-1' }],          // outdent/indent
            [{ 'header': [1, 2, 3, 4, 5, 6, false] }],
            [{ 'color': [] }, { 'background': [] }],          // dropdown with defaults from theme
            [{ 'font': [] }],
            [{ 'align': [] }],
            ['image', 'video'],
            ['clean']                                         // remove formatting button
        ];

        //ID選擇器：#editor <- 注意!
        let quill = new Quill('#editor', {
            modules: {
                toolbar: toolbarOptions
            },
            placeholder: '請輸入文章內容',
            theme: 'snow'
        });

        //確認發佈的click事件，註冊ajax事件
        $('#confirmPost').on('click', function () {
            //1. 取得文章的json內容
            let content = JSON.stringify(quill.getContents());
            let title = $("#postTitle").val();

            $.post(
                '@Url.Action("Create","Forum")',
                {
                    title: title,
                    content: content
                },
                function (response) {
                    console.log(response);
                }
            )
        })

        //設定定時觸發的ajax，獲得最新文章的資料()
        function refreshPostList() {
            //取得前一次的畫面內容時間，用來判斷那些文章有被異動過
            let prevDateTime = $("#prevGetTime").text();
            let lastPostId = @lastPostId;

            $.get(
                '@Url.Action("RefreshList","Forum")',
                {
                    lastPostId: lastPostId,
                    prevDtaetime: prevDateTime
                },
                function (responseDatas) {
                    //先更新ajax的info欄位
                    $("#prevGetTime").text(responseDatas.newTime);


                    //判斷是否有新增的文章
                    //1.處理刪除
                    //-------------------------

                    //2.處理新增
                    $.each(responseDatas.newForums, function (idx, value) {
                        let btnLike    = $('<button></button>').addClass('btn btn-primary').text('喜歡');    //喜歡
                        let btnHate    = $('<button></button>').addClass('btn btn-primary').text('討厭');    //討厭
                        let btnShare   = $('<button></button>').addClass('btn btn-primary').text('分享');    //分享
                        let btnFav     = $('<button></button>').addClass('btn btn-primary').text('收藏');    //收藏
                        let btnHide    = $('<button></button>').addClass('btn btn-primary').text('隱藏');    //隱藏
                        let btnEdit    = $('<button></button>').addClass('btn btn-primary').text('編輯');    //編輯
                        let btnStop    = $('<button></button>').addClass('btn btn-danger').text('停用');     //停用
                        

                        let br = $('<br />');

                        let postid = value.postId;
                        let url = '@Url.Action("PostView","Forum")?fPostId=' + postid;
                        let link = $('<a></a>');
                        let td = $('<td></td>');
                        let tr = $('<tr></tr>');
                        link.text(value.title).attr('href', url);

                        td.append(link).append(br).append(btnLike).append(btnHate).append(btnShare).append(btnFav).append(btnHide).append(btnEdit).append(btnStop);
                        tr.append(td);

                        $('tbody').append(tr);
                    })

                    //3.處理更新
                    //--------------------------

                    console.log("test");
                }
            )
        };

        window.setInterval(refreshPostList, 1000);
    </script>
}